# Generated by Django 5.2.13 on 2026-04-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_last_na_d5d12d_idx',
            old_name='patients_pa_last_na_0e36b0_idx',
        ),
        migrations.RenameIndex(
            model_name='patient',
            new_name='patients_pa_phone_fc49bb_idx',
            old_name='patients_pa_phone_404db2_idx',
        ),
    ]
