# Generated by Django 5.2.13 on 2026-04-25 12:19

import apps.telemedicine.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('facilities', '0001_initial'),
        ('patients', '0003_patient_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('waiting_patient', 'Waiting patient'), ('waiting_doctor', 'Waiting doctor'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=24)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_started_at', models.DateTimeField(blank=True, null=True)),
                ('actual_ended_at', models.DateTimeField(blank=True, null=True)),
                ('complaint', models.TextField(blank=True)),
                ('anamnesis', models.TextField(blank=True)),
                ('doctor_recommendations', models.TextField(blank=True)),
                ('diagnosis_text', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('jitsi_domain', models.CharField(default='meet.jit.si', max_length=255)),
                ('jitsi_room_name', models.CharField(default=apps.telemedicine.models.generate_room_name, max_length=255, unique=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_consultation', to='appointments.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_online_consultations', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_consultations', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_consultations', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('telemedicine', 'Telemedicine'), ('data_processing', 'Data processing')], max_length=32)),
                ('accepted_at', models.DateTimeField()),
                ('text_snapshot', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_consents', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='telemedicine.onlineconsultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='Teleconsilium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('conclusion', models.TextField(blank=True)),
                ('jitsi_domain', models.CharField(default='meet.jit.si', max_length=255)),
                ('jitsi_room_name', models.CharField(default=apps.telemedicine.models.generate_room_name, max_length=255, unique=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teleconsiliums', to='facilities.facility')),
                ('invited_doctors', models.ManyToManyField(blank=True, related_name='invited_teleconsiliums', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teleconsiliums', to='patients.patient')),
                ('primary_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_teleconsiliums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
            },
        ),
    ]
