# Generated by Django 5.2.13 on 2026-04-25 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0003_patient_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('appointment_type', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=16, verbose_name='Appointment type')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='requested', max_length=16, verbose_name='Status')),
                ('requested_datetime', models.DateTimeField(verbose_name='Requested datetime')),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled datetime')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duration (minutes)')),
                ('reason', models.TextField(verbose_name='Reason / complaint')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Cancellation reason')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='facilities.facility', verbose_name='Facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-requested_datetime', '-created_at'],
            },
        ),
    ]
